CREATE TABLE IF NOT EXISTS expenses (
    id SERIAL PRIMARY KEY,
    item VARCHAR(255) NOT NULL,
    cost NUMERIC(10, 2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    who_paid VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);